### ISSUE TITLE
Comparison to similar projects would be helpful

### ISSUE THREAD

**Issue by stevensonmt** [grego/caretaker#2]
I would be interested to see how this tool compares with others like cargo-watch, hotwatch, watchdo, watchdog, and fsw in terms of features, performance, and API.

**Comment by grego** [comment]
cargo-watch works only with cargo. The others you mentioned are libraries.
None is like caretaker, i.e a small binary able to watch multiple paths according to a config file.
Would you like me to write up some comparison nonetheless?

**Comment by stevensonmt** [comment]
I think only hotwatch is a lib rather than binary. Not sure if watchdog is still active as no repository is linked on the crates.io entry.

**Comment by grego** [comment]
Watchdog doesn't seem to be developed anymore.
Watchdo can only watch one directory at a time, although execute multiple commands after a change (a feature planned for caretaker). Same for fsw. As far as I can find, none of them is configurable.
I may add more thorough comparisons to the `README` with a new version. So far I'm closing the issue.
