### ISSUE TITLE
Please improve the error messages

### ISSUE THREAD

**Issue by ptsl** [grego/caretaker#4]
**Current error message:**

`$ caretaker                                                                                          
Error: Notify { source: Error { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), paths: [] } }`

**Expected error message:**
This is a matter of taste of course, but following the Unix/Linux practice, the following format would be fine:
`caretaker: error: no such file or directory: /home/me/test`

**Comment by ptsl** [comment]
**Nota Bene:**
The error message above was obtained using the default (`caretaker init`) `.watch.toml` file.
`path =  "src"`

Please note that the error message in question does not mention the nonexistent path (`src`). The "`paths:`" list is empty instead.

**Comment by grego** [comment]
Fixed in 20cf58279e09c566f047faab76dbbbe08c786d2c
