### ISSUE TITLE
Caretaker duplicates events for new files

### ISSUE THREAD

**Issue by ptsl** [grego/caretaker#5]
Given the most basic configuration:

    [[watch]]
    name = "print hello"
    path = "test"
    command = "echo $EVENT_PATH"

    # Verify that no other caretaker instance is running
    $ ps -e | egrep caretaker

    $ caretaker

    # Run in another terminal
    $ cd test
    $ touch abcd    # create a new file

    "/home/me/test/abcd" changed, running print hello
    /home/me/test/abcd
    "/home/me/test/abcd" changed, running print hello
    /home/me/test/abcd

The duplication does not occur for existing files.

**Comment by grego** [comment]
Fixed in 0cc610b640fe19ca161c3df05406510fac101cbc and published as v0.2.1

**Comment by ptsl** [comment]
Thank you for sorting this out. And the other issue too, of course.

**Comment by a-kenji** [comment]
Yes, thank you!
