### ISSUE TITLE
SHELL on Windows still passes /c

### ISSUE THREAD

**Issue by bugabinga** [grego/caretaker#6]
When running `caretaker` on Windows it respects the `SHELL` environment variable, which I expected, but it seems to try to pass `/c` to it, even, when the shell is not `cmd.exe`.

I believe the main problem is, that every shell has a different way to pass commands to it.
- cmd.exe /c
- powershell -Command
- nu --commands
- etc.

Reusing the `SHELL` variable leaves caretaker with the guesswork of how to pass a command.
Since `SHELL` is not exclusive to caretaker, it would be a bad idea to set it to `powershell -Command` for example.

How about adding a `CARETAKER_SHELL_COMMAND` variable with `SHELL` being used as a fallback?

**Comment by grego** [comment]
In 2e2bf18449ee700928a5af343b11a10bd919945d, I added an option to pass a custom command marker argument, either via `--arg` argument or via a `CARETAKER_ARG` environment variable.
E.g. `caretaker --arg -Command`

**Comment by bugabinga** [comment]
Very nice! Thanks
